version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: nepo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nepocorp
    ports:
      - "5440:5432"
    volumes:
      - nepo-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: nepo-redis
    ports:
      - "6390:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    container_name: nepo-adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  nepo-pgdata:
