import { useState, useEffect, useCallback } from 'react';
import {
  getPartners,
  addPartner,
  updatePartner,
  deletePartner,
  getPartnerByCode,
} from '@services/mockData/partners';

// Initial form state
const initialFormState = {
  code: '',
  name: '',
  address: '',
  taxCode: '',
};

const usePartnerManagement = () => {
  const [partners, setPartners] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Fetch all partners
  const fetchPartners = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const data = await getPartners();
      setPartners(data || []);
    } catch (err) {
      const errorMessage = err.message || 'Không thể tải danh sách đối tác';
      setError(errorMessage);
      console.error('Error fetching partners:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  // Add new partner
  const addNewPartner = useCallback(
    async partnerData => {
      setLoading(true);
      setError('');
      try {
        // Always generate a new code for new partners
        const newPartner = await addPartner(partnerData);
        // Refresh the partner list
        await fetchPartners();
        return { success: true, data: newPartner };
      } catch (err) {
        const errorMessage = err.message || 'Lỗi khi thêm đối tác';
        setError(errorMessage);
        console.error('Error adding partner:', err);
        return { success: false, error: errorMessage };
      } finally {
        setLoading(false);
      }
    },
    [fetchPartners]
  );

  // Get initial form data with generated code
  const getInitialFormData = useCallback(() => {
    // The code will be generated by the mock API
    return { ...initialFormState };
  }, []);

  // Check if a partner code is available
  const isPartnerCodeAvailable = useCallback(async (code, excludeId = null) => {
    if (!code || code.trim() === '') return false;

    try {
      const response = await getPartnerByCode(code);
      // If we're excluding an ID (for updates), it's okay if it's the same partner
      if (excludeId && response.data && response.data.id === excludeId) {
        return true;
      }
      return false;
    } catch (err) {
      // 404 means code is available
      return err.response?.status === 404;
    }
  }, []);

  // Update existing partner
  const updateExistingPartner = async (id, partnerData) => {
    setLoading(true);
    setError('');
    try {
      const updatedPartner = await updatePartner(id, partnerData);
      // Refresh the partner list
      await fetchPartners();
      return { success: true, data: updatedPartner };
    } catch (err) {
      const errorMessage = err.message || 'Lỗi khi sửa đối tác';
      setError(errorMessage);
      console.error('Error updating partner:', err);
      return { success: false, error: errorMessage };
    } finally {
      setLoading(false);
    }
  };

  // Delete partner
  const deleteExistingPartner = async id => {
    setLoading(true);
    setError('');
    try {
      await deletePartner(id);
      // Remove from local state immediately for better UX
      setPartners(prev => prev.filter(p => p.id !== id));
      return { success: true };
    } catch (err) {
      const errorMessage = err.message || 'Lỗi khi xóa đối tác';
      setError(errorMessage);
      console.error('Error deleting partner:', err);
      // Refresh the list in case of error to ensure consistency
      await fetchPartners();
      return { success: false, error: errorMessage };
    } finally {
      setLoading(false);
    }
  };

  // Get partner by ID
  const getPartnerById = async id => {
    try {
      const partner = partners.find(p => p.id === id);
      if (partner) {
        return { success: true, data: partner };
      } else {
        return { success: false, error: 'Không tìm thấy đối tác' };
      }
    } catch (err) {
      const errorMessage = err.message || 'Không tìm thấy đối tác';
      console.error('Error getting partner by ID:', err);
      return { success: false, error: errorMessage };
    }
  };

  // Clear error
  const clearError = () => setError('');

  // Initial fetch on mount
  useEffect(() => {
    fetchPartners();
  }, [fetchPartners]);

  return {
    // State
    partners,
    loading,
    error,

    // Actions
    fetchPartners,
    addPartner: addNewPartner,
    updatePartner: updateExistingPartner,
    deletePartner: deleteExistingPartner,
    getPartnerById,
    isPartnerCodeAvailable,
    getInitialFormData,
    clearError,
  };
};

export default usePartnerManagement;
