import { TripStatus, FuelMode } from '@nepocorp/shared';

// Helper to create date relative to now
const date = (daysFromNow: number) => {
  const now = new Date();
  const baseDate = new Date(now.getTime() - 90 * 86400000); // 3 months ago
  return new Date(baseDate.getTime() + daysFromNow * 86400000).toISOString().slice(0, 10);
};

export const trips = [
  // ===== MONTH 1: Mixed results =====

  // 1. Normal profitable trip
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(1),
      status: TripStatus.LOCKED,
      revenue: '4500000',
      revenueOriginal: '4500000',
      fuelLiters: '85',
      totalFuelCost: '1955000',
      totalRoadAllowance: '950000',
      driverSalary: '500000',
      totalCost: '3405000',
      grossProfit: '1095000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 2. Mountain route loss (high fuel consumption)
  {
    customerName: 'Công ty TNHH Logistics XYZ',
    routeName: 'Hà Nội - Mộc Châu',
    truckPlate: '30A-67890',
    trailerPlate: '30R-0002',
    driverName: 'Phạm Đức Minh',
    cargoType: 'Chè',
    data: {
      departureDate: date(3),
      status: TripStatus.LOCKED,
      revenue: '6000000',
      revenueOriginal: '6000000',
      fuelLiters: '248',
      totalFuelCost: '5704000',
      totalRoadAllowance: '1100000',
      driverSalary: '700000',
      totalCost: '7504000',
      grossProfit: '-1504000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '8',
      fuelSupplementReason: 'Đèo Cao - đường đèo dốc',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 3. Long distance profitable
  {
    customerName: 'Công ty Xuất nhập khẩu DEF',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '29C-11111',
    trailerPlate: '30R-0003',
    driverName: 'Hoàng Nam',
    cargoType: 'Container 20ft',
    data: {
      departureDate: date(5),
      status: TripStatus.LOCKED,
      revenue: '12000000',
      revenueOriginal: '12000000',
      fuelLiters: '315',
      totalFuelCost: '7245000',
      totalRoadAllowance: '2200000',
      driverSalary: '900000',
      totalCost: '10345000',
      grossProfit: '1655000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 4. Break-even trip
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(8),
      status: TripStatus.LOCKED,
      revenue: '4200000',
      revenueOriginal: '4500000',
      fuelLiters: '88',
      totalFuelCost: '2024000',
      totalRoadAllowance: '950000',
      driverSalary: '500000',
      totalCost: '3474000',
      grossProfit: '726000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 5. Small loss
  {
    customerName: 'Đông Á Logistics',
    routeName: 'Hà Nội - Thái Nguyên',
    truckPlate: '29H-98765',
    trailerPlate: '30R-0004',
    driverName: 'Nguyễn Văn Hùng',
    cargoType: 'Hàng rời',
    data: {
      departureDate: date(11),
      status: TripStatus.LOCKED,
      revenue: '6500000',
      revenueOriginal: '6500000',
      fuelLiters: '295',
      totalFuelCost: '6785000',
      totalRoadAllowance: '1050000',
      driverSalary: '800000',
      totalCost: '8635000',
      grossProfit: '-2135000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // ===== MONTH 2: Good performance =====

  // 6. Very profitable with return cargo
  {
    customerName: 'Công ty TNHH Logistics XYZ',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '30A-67890',
    trailerPlate: '30R-0002',
    driverName: 'Phạm Đức Minh',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(32),
      status: TripStatus.LOCKED,
      revenue: '5800000',
      revenueOriginal: '4500000',
      fuelLiters: '80',
      totalFuelCost: '1840000',
      totalRoadAllowance: '850000',
      driverSalary: '500000',
      totalCost: '3190000',
      grossProfit: '2610000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: true,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 7. Mountain route with supplement
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hà Nội - Sơn La',
    truckPlate: '29C-11111',
    trailerPlate: '30R-0003',
    driverName: 'Hoàng Nam',
    cargoType: 'Container 20ft',
    data: {
      departureDate: date(35),
      status: TripStatus.LOCKED,
      revenue: '8000000',
      revenueOriginal: '8000000',
      fuelLiters: '335',
      totalFuelCost: '7705000',
      totalRoadAllowance: '1300000',
      driverSalary: '850000',
      totalCost: '9855000',
      grossProfit: '-1855000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '15',
      fuelSupplementReason: 'Đèo Pha Luông - đường dốc liên tục',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 8. Standard trip
  {
    customerName: 'Công ty Xuất nhập khẩu DEF',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(38),
      status: TripStatus.LOCKED,
      revenue: '4600000',
      revenueOriginal: '4500000',
      fuelLiters: '83',
      totalFuelCost: '1909000',
      totalRoadAllowance: '950000',
      driverSalary: '500000',
      totalCost: '3359000',
      grossProfit: '1241000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 9. Multiple tolls
  {
    customerName: 'Vinh Phát Trading',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '29H-98765',
    trailerPlate: '30R-0003',
    driverName: 'Nguyễn Văn Hùng',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(41),
      status: TripStatus.LOCKED,
      revenue: '12500000',
      revenueOriginal: '12000000',
      fuelLiters: '325',
      totalFuelCost: '7475000',
      totalRoadAllowance: '2200000',
      driverSalary: '900000',
      totalCost: '10575000',
      grossProfit: '1925000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '200000',
      tollsStations: 5,
    },
  },

  // 10. Toll discount
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '30A-67890',
    trailerPlate: '30R-0002',
    driverName: 'Phạm Đức Minh',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(44),
      status: TripStatus.LOCKED,
      revenue: '4400000',
      revenueOriginal: '4500000',
      fuelLiters: '86',
      totalFuelCost: '1978000',
      totalRoadAllowance: '850000',
      driverSalary: '500000',
      totalCost: '3328000',
      grossProfit: '1072000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '100000',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 11. Profitable mountain route
  {
    customerName: 'Hoàng Long Transport',
    routeName: 'Hà Nội - Lạng Sơn',
    truckPlate: '29C-24680',
    trailerPlate: '30R-0006',
    driverName: 'Trần Thị Thương',
    cargoType: 'Gạo',
    data: {
      departureDate: date(47),
      status: TripStatus.LOCKED,
      revenue: '7200000',
      revenueOriginal: '7500000',
      fuelLiters: '195',
      totalFuelCost: '4485000',
      totalRoadAllowance: '900000',
      driverSalary: '750000',
      totalCost: '6135000',
      grossProfit: '1065000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 12. Long distance with return cargo
  {
    customerName: 'Tân Phú Freight',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '30H-13579',
    trailerPlate: '30R-0007',
    driverName: 'Vũ Minh Đức',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(50),
      status: TripStatus.LOCKED,
      revenue: '14000000',
      revenueOriginal: '12000000',
      fuelLiters: '305',
      totalFuelCost: '7015000',
      totalRoadAllowance: '2200000',
      driverSalary: '900000',
      totalCost: '10115000',
      grossProfit: '3885000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: true,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // ===== MONTH 3: Mixed with issues =====

  // 13. High fuel consumption warning
  {
    customerName: 'Công ty TNHH Logistics XYZ',
    routeName: 'Hà Nội - Mộc Châu',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Chè',
    data: {
      departureDate: date(60),
      status: TripStatus.LOCKED,
      revenue: '6200000',
      revenueOriginal: '6000000',
      fuelLiters: '295',
      totalFuelCost: '6785000',
      totalRoadAllowance: '1100000',
      driverSalary: '700000',
      totalCost: '8585000',
      grossProfit: '-2385000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '55',
      fuelSupplementReason: 'Xe cũ - động cơ yếu tiêu hao cao',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 14. Canceled trip
  {
    customerName: 'Công ty Xuất nhập khẩu DEF',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '29C-11111',
    trailerPlate: '30R-0003',
    driverName: 'Hoàng Nam',
    cargoType: 'Container 20ft',
    data: {
      departureDate: date(63),
      status: TripStatus.CANCELED,
      notes: 'Khách hàng hủy chuyến gấp do thay đổi kế hoạch',
    },
  },

  // 15. Very profitable long distance
  {
    customerName: 'Đông Á Logistics',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(66),
      status: TripStatus.LOCKED,
      revenue: '13000000',
      revenueOriginal: '12000000',
      fuelLiters: '310',
      totalFuelCost: '7130000',
      totalRoadAllowance: '2200000',
      driverSalary: '900000',
      totalCost: '10230000',
      grossProfit: '2770000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: true,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 16. Completed waiting approval - small loss
  {
    customerName: 'Vinh Phát Trading',
    routeName: 'Hà Nội - Sơn La',
    truckPlate: '30A-67890',
    trailerPlate: '30R-0002',
    driverName: 'Phạm Đức Minh',
    cargoType: 'Hàng rời',
    data: {
      departureDate: date(69),
      status: TripStatus.COMPLETED,
      revenue: '7800000',
      revenueOriginal: '7500000',
      fuelLiters: '285',
      totalFuelCost: '6555000',
      totalRoadAllowance: '1300000',
      driverSalary: '750000',
      totalCost: '8605000',
      grossProfit: '-805000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 17. Completed waiting approval - profitable
  {
    customerName: 'Hoàng Long Transport',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '29H-98765',
    trailerPlate: '30R-0004',
    driverName: 'Nguyễn Văn Hùng',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(72),
      status: TripStatus.COMPLETED,
      revenue: '4700000',
      revenueOriginal: '4500000',
      fuelLiters: '84',
      totalFuelCost: '1932000',
      totalRoadAllowance: '950000',
      driverSalary: '500000',
      totalCost: '3382000',
      grossProfit: '1318000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 18. Completed waiting approval - mountain route
  {
    customerName: 'Tân Phú Freight',
    routeName: 'Hà Nội - Thái Nguyên',
    truckPlate: '29C-24680',
    trailerPlate: '30R-0006',
    driverName: 'Trần Thị Thương',
    cargoType: 'Cà phê',
    data: {
      departureDate: date(75),
      status: TripStatus.COMPLETED,
      revenue: '6800000',
      revenueOriginal: '6500000',
      fuelLiters: '278',
      totalFuelCost: '6394000',
      totalRoadAllowance: '1050000',
      driverSalary: '780000',
      totalCost: '8224000',
      grossProfit: '-1424000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // 19. Short trip profitable
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hải Phòng - Bắc Ninh',
    truckPlate: '30H-13579',
    trailerPlate: '30R-0007',
    driverName: 'Vũ Minh Đức',
    cargoType: 'Container 20ft',
    data: {
      departureDate: date(78),
      status: TripStatus.LOCKED,
      revenue: '3800000',
      revenueOriginal: '3800000',
      fuelLiters: '65',
      totalFuelCost: '1495000',
      totalRoadAllowance: '700000',
      driverSalary: '450000',
      totalCost: '2645000',
      grossProfit: '1155000',
      fuelMode: FuelMode.AUTO,
      hasReturnCargo: false,
      fuelPriceApplied: '23000',
      fuelSupplementLiters: '0',
      tollsDiscount: '0',
      tollsAddition: '0',
      tollsStations: 0,
    },
  },

  // ===== CURRENT MONTH: Active trips =====

  // 20. Currently in transit
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(-2),
      status: TripStatus.IN_TRANSIT,
    },
  },

  // 21. Currently in transit - mountain route
  {
    customerName: 'Công ty TNHH Logistics XYZ',
    routeName: 'Hà Nội - Mộc Châu',
    truckPlate: '29C-11111',
    trailerPlate: '30R-0003',
    driverName: 'Hoàng Nam',
    cargoType: 'Chè',
    data: {
      departureDate: date(-1),
      status: TripStatus.IN_TRANSIT,
    },
  },

  // 22. Created, waiting dispatch - urgent
  {
    customerName: 'Công ty Xuất nhập khẩu DEF',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '30A-67890',
    trailerPlate: '30R-0002',
    driverName: 'Phạm Đức Minh',
    cargoType: 'Container 20ft',
    data: {
      departureDate: date(0),
      status: TripStatus.CREATED,
      notes: 'Hàng 40ft vỏ rỗng, cần xe gấp - khách VIP',
    },
  },

  // 23. Created, waiting dispatch
  {
    customerName: 'Đông Á Logistics',
    routeName: 'Hà Nội - Lạng Sơn',
    truckPlate: '29H-98765',
    trailerPlate: '30R-0004',
    driverName: 'Nguyễn Văn Hùng',
    cargoType: 'Hàng rời',
    data: {
      departureDate: date(0),
      status: TripStatus.CREATED,
    },
  },

  // 24. Created, waiting dispatch - tomorrow
  {
    customerName: 'Vinh Phát Trading',
    routeName: 'Hà Nội - Hải Phòng',
    truckPlate: '29C-24680',
    trailerPlate: '30R-0006',
    driverName: 'Trần Thị Thương',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(1),
      status: TripStatus.CREATED,
      notes: 'Xuất phát sáng mai 6:00',
    },
  },

  // 25. Created, waiting dispatch - urgent
  {
    customerName: 'Hoàng Long Transport',
    routeName: 'Hà Nội - Mộc Châu',
    truckPlate: '30H-13579',
    trailerPlate: '30R-0007',
    driverName: 'Vũ Minh Đức',
    cargoType: 'Gạo',
    data: {
      departureDate: date(0),
      status: TripStatus.CREATED,
      notes: 'Khách hàng yêu cầu xuất phát 14:00 hôm nay',
    },
  },

  // 26. Created, waiting dispatch
  {
    customerName: 'Tân Phú Freight',
    routeName: 'Hà Nội - Đà Nẵng',
    truckPlate: '30A-12345',
    trailerPlate: '30R-0001',
    driverName: 'Lê Văn Tài',
    cargoType: 'Container 40ft',
    data: {
      departureDate: date(1),
      status: TripStatus.CREATED,
    },
  },

  // 27. Created, waiting dispatch - special cargo
  {
    customerName: 'Công ty CP Vận tải ABC',
    routeName: 'Hà Nội - Thái Nguyên',
    truckPlate: '29C-11111',
    trailerPlate: '30R-0003',
    driverName: 'Hoàng Nam',
    cargoType: 'Cà phê',
    data: {
      departureDate: date(2),
      status: TripStatus.CREATED,
      notes: 'Hàng đặc biệt cần chụp ảnh',
    },
  },

  // 28. Created, waiting dispatch
  {
    customerName: 'Công ty TNHH Logistics XYZ',
    routeName: 'Hải Phòng - Hà Nam',
    truckPlate: '30A-67890',
    trailerPlate: '30R-0002',
    driverName: 'Phạm Đức Minh',
    cargoType: 'Vải sợi',
    data: {
      departureDate: date(1),
      status: TripStatus.CREATED,
    },
  },

  // 29. Created, waiting dispatch
  {
    customerName: 'Đông Á Logistics',
    routeName: 'Hà Nội - Quảng Ninh',
    truckPlate: '29H-98765',
    trailerPlate: '30R-0004',
    driverName: 'Nguyễn Văn Hùng',
    cargoType: 'Container 20ft',
    data: {
      departureDate: date(2),
      status: TripStatus.CREATED,
    },
  },

  // 30. Created, waiting dispatch
  {
    customerName: 'Vinh Phát Trading',
    routeName: 'Hà Nội - Sơn La',
    truckPlate: '29C-24680',
    trailerPlate: '30R-0006',
    driverName: 'Trần Thị Thương',
    cargoType: 'Hàng rời',
    data: {
      departureDate: date(3),
      status: TripStatus.CREATED,
    },
  },
];
